// angular-elements/projects/angular-elements/src/lib/m-modal/m-modal.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  selector: 'm-modal',
  styleUrls: ['m-modal.scss'],
  template: `
      <dialog class="m-modal" [open]="open">
        <div class="m-modal__content">
          <p>Da modal</p>
          <m-button (click)="close()">Close</m-button>
        </div>
      </dialog>
  `,
})
export class MModal {
  @Input() open: boolean = false;
  @Output() dismiss: EventEmitter<boolean> = new EventEmitter();

  close() {
    this.dismiss.emit(false);
    this.open = false;
  }
}

// src/components/m-modal/m-modal.tsx
import { Component, Event, EventEmitter, Prop, Watch, h } from '@stencil/core';

@Component({
  tag: 'm-modal',
  styleUrl: 'm-modal.scss',
  shadow: true
})
export class Modal {
  @Prop() open: boolean = false;
  @Watch('open') watchOpen() {}
  @Event() dismiss: EventEmitter;

  close() {
    this.dismiss.emit(false);
    this.open = false;
  }

  render() {
    return (
      <dialog class="m-modal" open={this.open}>
        <div class="m-modal__content">
          <p>Da modal</p>
          <m-button onClick={ () => this.close() }>Close</m-button>
        </div>
      </dialog>
    );
  }
}
