// angular-elements/projects/angular-elements/src/lib/m-complex-modal/m-complex-modal.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

export type ComplexModalContents = {
  title: string,
  content: string,
  footer: string,
};

@Component({
  selector: 'm-complex-modal',
  styleUrls: ['m-complex-modal.scss'],
  template: `
      <dialog class="m-complex-modal" open="open">
        <div class="m-complex-modal__content">
          <h1>{{ contents?.title }}</h1>
          <p>{{ contents?.content }}</p>
          <footer>
            <p>{{ contents?.footer }}</p>
            <m-button (click)="close()">Close</m-button>
          </footer>
        </div>
      </dialog>
  `
})
export class MComplexModal {
  @Input() open: boolean = false;
  @Input() contents: ComplexModalContents = {
    title: '',
    content: '',
    footer: '',
  };
  @Output() dismiss: EventEmitter<boolean> = new EventEmitter();

  close() {
    this.dismiss.emit(false);
    this.open = false;
  }
}

// src/components/m-complex-modal/m-complex-modal.tsx
import { Component, Event, EventEmitter, Prop, h } from '@stencil/core';

export type ComplexModalContents = {
  title: string,
  content: string,
  footer: string,
};

@Component({
  tag: 'm-complex-modal',
  styleUrl: 'm-complex-modal.scss',
  shadow: true
})
export class ComplexModal {
  @Prop({ reflect: true }) open: boolean = false;
  @Prop({ reflect: true }) contents: ComplexModalContents = {
    title: '',
    content: '',
    footer: '',
  };
  @Event() dismiss: EventEmitter;

  close() {
    this.dismiss.emit(false);
    this.open = false;
  }

  render() {
    return (
      <dialog class="m-complex-modal" open={this.open}>
        <div class="m-complex-modal__content">
          <h1>{this.contents.title}</h1>
          <p>{this.contents.content}</p>
          <footer>
            <p>{this.contents.footer}</p>
            <m-button onClick={ () => this.close() }>Close</m-button>
          </footer>
        </div>
      </dialog>
    );
  }
}
