// ng-src/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
	public isModalOpen: boolean = false;
  public isPanelOpen: boolean = false;

  @HostListener('dismiss', ['$event.target'])
  onModalDismiss() {
    this.isModalOpen = false;
    this.isPanelOpen = false;
  }

	openModal() {
		this.isModalOpen = true;
	}

  openPanel() {
    this.isPanelOpen = true;
  }
}

<h1>A nice Angular app</h1>
<m-modal [open]="isModalOpen"></m-modal>
<m-panel [open]="isPanelOpen"></m-panel>
<m-button (click)="openModal()">Open modal</m-button>
<m-button (click)="openPanel()">Open panel</m-button>

// react-src/src/App.tsx
import React from 'react';
import ReactDOM from 'react';
import logo from './logo.svg';
import './App.css';

type AppProps = {};
type AppState = {
  isModalOpen: boolean,
  isPanelOpen: boolean,
};

class App extends React.Component<AppProps, AppState> {
  constructor(props: any) {
    super(props);
    this.state = {
      isModalOpen: false,
      isPanelOpen: false,
    };
  }

  openModal() {
    this.setState({ isModalOpen: true });
  }

  openPanel() {
    this.setState({ isPanelOpen: true });
  }

  render() {
    return (
      <main>
        <h1>A nice React app</h1>
        <m-button onClick={ () => this.openModal() }>Open modal</m-button>
        <m-button onClick={ () => this.openPanel() }>Open panel</m-button>
        <m-modal open={ this.state.isModalOpen } ></m-modal>
        <m-panel open={ this.state.isPanelOpen } ></m-panel>
      </main>
    );
  }
}

export default App;
